server :
  port : 8000

spring :
  main :
    web-application-type : reactive
  application :
    name : api-gateway
  cloud :
    gateway :
     routes :
     - id : user-service
       uri : http://localhost:8001/
       predicates :
       - Path=/user/**

     - id : order-service
       uri : http://localhost:8002/
       predicates :
       - Path=/order/**

     - id : inventory-service
       uri : http://localhost:8003/
       predicates :
       - Path=/inventory/**
